plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sweetwheel.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.sweetwheel.app"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile rootProject.file('app.keystore')
            storePassword 'android123'
            keyAlias 'twa'
            keyPassword 'android123'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
